### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/r-python-exercise1-ajinkyapdeshmukh#1]
Hi Ajinkya, 

Really great job on the assignment. No concerns. Please keep the format of this submission in mind for future assignments. 

I am giving you full credit, no revisions needed. 
-Greg

**Comment by ajinkyapdeshmukh10** [comment]
Hello Greg, 

Thank you for the feedback, I'll keep in mind the format of the submission for future assignments.

-Ajinkya
